name: 📋 タスク
description: 開発タスクや作業項目
title: "[Task] "
labels: ["task"]
projects: ["kpab/1"]
assignees:
  - kpab
body:
  - type: markdown
    attributes:
      value: |
        開発タスクを作成します。

  - type: textarea
    id: description
    attributes:
      label: 📝 タスクの説明
      description: 何をする必要がありますか？
      placeholder: 具体的なタスク内容を記述...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: ✅ 完了条件
      description: このタスクが完了したと判断する条件
      placeholder: |
        - [ ] ○○が実装されている
        - [ ] ○○のテストが通る
        - [ ] ○○の確認が完了している
    validations:
      required: true

  - type: textarea
    id: technical_notes
    attributes:
      label: 🔧 技術的メモ
      description: 実装に関する技術的な注意点やヒント
      placeholder: 使用する技術、注意点、参考資料など...

  - type: dropdown
    id: category
    attributes:
      label: 📂 カテゴリ
      description: このタスクのカテゴリは？
      options:
        - Frontend - フロントエンド開発
        - Backend - バックエンド開発
        - Database - データベース作業
        - Infrastructure - インフラ・DevOps
        - Testing - テスト作成・実行
        - Documentation - ドキュメント作成
        - Design - UI/UXデザイン
        - Research - 調査・検証
        - Bug Fix - バグ修正
        - Refactoring - リファクタリング
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🚨 優先度
      description: このタスクの優先度は？
      options:
        - Low (低)
        - Medium (中)
        - High (高)
        - Critical (緊急)
      default: 1
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: ⏱️ 想定工数
      description: このタスクの実装にかかる時間は？
      options:
        - XS (30分以内)
        - S (1-2時間)
        - M (半日)
        - L (1日)
        - XL (2-3日)
        - XXL (1週間以上)
      default: 2
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: 🔗 依存関係
      description: このタスクの前に完了が必要な他のタスクやIssue
      placeholder: "#123 が完了してから実施"